### ISSUE TITLE
Compile project to WebAssembly

### ISSUE THREAD

**Issue by henne90gen** [henne90gen/graphics_playground#1]
# TODOs
- [x] create a proper `index.html`
- [ ] create a nice `scene.html`
- [x] create favicon

# Scenes
## A Star
- runs
- [ ] main texture is not being rendered

## Ambient Occlusion
- runs
- 3D Objects are visible
- [ ] ambient occlusion does not work yet (SSAO texture is black instead of having the AO data)

## Audio Vis
- rendering the empty scene works
- [ ] find way to load sound file

## Bloom Effect
- all shaders compile
- runs
- [ ] find a way to load model
- [ ] find out what is wrong with framebuffer

## DTM Viewer
- skipped for now

## Font Demo
- [ ] find way to load font file
- [ ] add font file to repo

## Framebuffer Demo
- runs
- [ ] find out why framebuffer does not work

## GraphVis
- runs somewhat
- [ ] find a way around glVertexAttribDivisor (maybe use a geometry shader)

## Landscape
- [ ] haven't tried to convert this scene yet

## Legacy Triangle
- does not work
- needs further investigation

## Light Demo
- runs
- [ ] find a way to load model in frontend

## Mine Sweeper
- runs
- [ ] find a way to load font file

## Model Loading
- runs
- [ ] find a way to load models

## Normal Mapping
- runs
- [ ] find a way to load models

## Ray Tracing
- runs
- [ ] texture does not render correctly

## Shadows 2D
- does not run
- shaders compile correctly
- [ ] investigate why it does not work (probably because of stencil magic)

## Terrain Erosion
- shaders compile
- glEnable(GL_PRIMITIVE_RESTART) is not supported by WebGL
- [ ] find an alternative for GL_PRIMITIVE_RESTART

## Tessellation
- is not supported by WebGL
